apiVersion: batch/v1
kind: CronJob
metadata:
  name: es-watcher-cronjob
  namespace: elastic-stack
spec:
  schedule: "* */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: es-watcher-sa
          containers:
          - name: es-watcher
            image: alpine:latest
            command:
            - /bin/sh
            - -c
            - apk add kubectl jq && /config/watcher.sh
            volumeMounts:
            - name: config
              mountPath: /config
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: es-watcher-config
              defaultMode: 493