apiVersion: v1
kind: ConfigMap
metadata:
  name: es-watcher-config
  namespace: elastic-stack
data:
  watcher.sh: |
    #!/bin/sh
    set -e
    kubectl -n elastic-stack get pods --field-selector=status.phase=Pending -o json | \
    jq -r '.items[] | select(.status.containerStatuses[].state.waiting.reason=="CreateContainerError") | .metadata.name' | \
    while read pod; do
      kubectl -n elastic-stack delete pod $pod
    done