---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-watcher-sa
  namespace: elastic-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: elastic-stack
  name: es-watcher-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: es-watcher-rb
  namespace: elastic-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: es-watcher-role
subjects:
- kind: ServiceAccount
  name: es-watcher-sa
  namespace: elastic-stack